# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build and Deploy

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build Project with Gradle
        run: chmod +x ./gradlew && ./gradlew build

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker Image
        run: docker build -t heartlash/mahashaktibe .

      - name: Publish Image to Docker Hub
        run: docker push heartlash/mahashaktibe:latest

  deploy:
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      # Step to create the .pem file on the runner from the secret
      - name: Create Server Secret File
        run: |
          echo "${{ secrets.MAHASHAKTI_SERVER_KEY }}" > mahashakti-server-key.pem
          chmod 600 mahashakti-server-key.pem

      - name: Deploy to Mahashakti-Server
        run: |
          ssh -o StrictHostKeyChecking=no -i mahashakti-server-key.pem ubuntu@15.207.117.182 "
            docker pull heartlash/mahashaktibe:latest &&
            docker stop mahashakti-app || true &&
            docker rm mahashakti-app || true &&
            docker run -d --name mahashakti-app -e SPRING_PROFILES_ACTIVE=prod -p 8080:8080 heartlash/mahashaktibe:latest
          "